/*####################################################################################################################*/
/*                                                                                                                    */
/*                                              Includes for XTP-Objects                                              */
/*                                                                                                                    */
/*####################################################################################################################*/
/*                                                                                                                    */
/*                             Contains all defines and data structures which are used for                            */
/*                                                 XTP-Communication.                                                 */
/*                       The structure of the objects does not include the header of the object.                      */
/*                                          Programming language: C ( ANSI )                                          */
/*                                                                                                                    */
/*####################################################################################################################*/
/*                                                                                                                    */
/*                                                 FILENAME: xtpobj.h                                                 */
/*                                       FISRT CREATE: 2017-03-26                                                     */
/*                                                                                                                    */
/*####################################################################################################################*/


#ifndef XTPOBJ_H_
#define XTPOBJ_H_
#ifdef _WINDOWS
#include "portabnt.h"
#else
#include "Types.h"
#endif

#define XTP_MODE_BROADCAST   0x00          /* the object can be received by all targets which have it in their inlist */
#define XTP_MODE_DIRECT      0x01          /* the object is sent only to the target directly addressed */
#define XTP_MODE_SYSTEM      0x02          /* only of messages (objects) generated by XTP Server */
#define XTP_MODE_MANAGE      0x03          /* Objects only used by Manage */



#ifdef _WINDOWS
#define XTP_DEF_PACKED

#define ID_UPDATA_LIST_BOX       (WM_USER+101)
#else
#define XTP_DEF_PACKED __attribute__ ((packed))  
#endif
#ifdef _WINDOWS
#pragma pack (push, 1)
#endif

#define SCONNECT 0x0002 /* Object-ID */
typedef struct
{
	uint16			no_objects;		/* number of objects */
} XTP_DEF_PACKED sconnect_t1;

typedef struct
{
	uint16			object_id;		/* ID of the object */
} XTP_DEF_PACKED sconnect_t2;

//PC->Target
const uint16 ExtID_Manager  = 0x1001;
const uint16 ExtID_SimuSend = 0x1010;

//Target->PC
const uint16 ExtID_ObjFlow_Info = 0x1101;
const uint16 ExtID_SimuOperate  = 0x1102;
const uint16 ExtID_XtpStatus    = 0x1103;


typedef uint16 XTP_MAN_TYPE;
const XTP_MAN_TYPE SIMU_IP_SET = 10;
typedef struct  
{
	uint64  SimuIp;
	uint16 SimuPort;
}XTP_DEF_PACKED SIMU_IP_SET_t;


typedef struct
{
	uint16 ExtID;
	uint16 FrameLen;
} XTP_DEF_PACKED Comm_XTP_ExtHeader;

typedef struct
{
	uint16 ExtID;
	uint16 FrameLen;
	char  data[256];
} XTP_DEF_PACKED Comm_XTP_Ext;

typedef struct
{
    uint16 length; //contain the header length, i.e. the minimal lenght of XTP telegram is 8. Max value is 1032
    uint16 telID;
    uint8  sender;
    uint8  target;
    uint8  mode;
    uint8  dummy;
}XTP_DEF_PACKED tXtpObjHeader;




#ifdef _WINDOWS
#pragma pack (pop)
#endif 

#define SYS_OK 1

#endif /* XTPOBJ_H_ */
